### ISSUE TITLE
cannot find Facebook user - authorization code 

### ISSUE THREAD

**Issue by elvinkao** [ericbae/Tank-Auth---3rd-Party-Authentication-Project#1]
I have used other facebook packages and have been stuck when after authorization, facebook returns an authorization code

http://YOUR_URL?code=A_CODE_GENERATED_BY_SERVER

Do you have any idea why?

**Comment by ericbae** [comment]
Hey there Kingkao. 

Hm. That error seems quite new. Can you tell me the site that you are testing with? Maybe I can try it out. I know for sure that testing Facebook plugin locally isn't very friendly and whenever I tried to test Facebook authentication, I always tested on the actual server. Let  me know buddy.

**Comment by elvinkao** [comment]
Thanks for looking into this. I just copied some of the file that you have changed from original codeigniter 2.0 and mixed it up with my previous site. 
Just did a fresh start with your code and it works. You've done a heck of a job. Going to slowly work my way into it.
Sorry about that.
