### ISSUE TITLE
fb and tw session not unset

### ISSUE THREAD

**Issue by rjdjohnston** [ericbae/Tank-Auth---3rd-Party-Authentication-Project#3]
The logout method in auth.php needs to be updated to include clearing twitter and fb id values.  You could put this in the library but just in case you are maintaining the core lib integrity I added to auth.php as below

```
/**
 * Logout user
 *
 * @return void
 */
function logout()
{
    $this->tank_auth->logout();
            $this->session->set_userdata(array('twitter_id' => '', 'facebook_id' => ''));

    $this->_show_message($this->lang->line('auth_message_logged_out'));
}
```

**Comment by ericbae** [comment]
Nice one. I fixed as you suggested and committed them! Thanks!
