### ISSUE TITLE
User object from FB not returning

### ISSUE THREAD

**Issue by rjdjohnston** [ericbae/Tank-Auth---3rd-Party-Authentication-Project#4]
Eric,

The user object does not appear to return after a new user signs up using FB.  This leads to the FB user id not being added in the database.  I notice this occuring when a tester has SSL activate in their FB account.

I am guessing this issue coincides with the SSL issue/solution posted on the fb library author's tutorial (page #5).  

Have you noticed this OR can you confirm the bug?

Thanks

**Comment by ericbae** [comment]
Hm. I never actually tested this on the SSL, so no this is new to me. I'll try it myself and see what's happening.

**Comment by rjdjohnston** [comment]
did u fix this?

**Comment by ericbae** [comment]
I haven't been able to test and reproduce this on my machine actually. sorry for the late reply. might have to set my environment up for closer inspection.

**Comment by rjdjohnston** [comment]
No worries, you can close the issue for now.  If it re-surfaces I will let you know and post a fix.

Thanks

Please pardon the brevity, this message was sent from my iPhone.

**Comment by ericbae** [comment]
Thanks for the feedback man! really appreciate it!
